### PR TITLE
Bump jazzy to 1.3.1

### PR DESCRIPTION
**Pull request by MichaelOrlov**
- Create a new release on Jazzy branch.
- Part of the https://github.com/ros-tooling/topic_tools/issues/108

### CODE REVIEW

**Review by christophebedard — APPROVED** [review]
Remember to tag the commit on `jazzy` after this PR is merged, unless you want to push the same commit to `jazzy` directly.

**Comment by MichaelOrlov** [comment]
@christophebedard Can you please elaborate on 
> Remember to tag the commit on jazzy after this PR is merged, unless you want to push the same commit to jazzy directly.

I didn't get it. What do you mean by that?
I already have a tag https://github.com/ros-tooling/topic_tools/releases/tag/1.3.1 which is pointing out to the my commit https://github.com/ros-tooling/topic_tools/commit/29ff91fd54b032e0925d58d3b7f9c9711c6cf85d and it is only one commit on my branch in the ~rosbag2~ topic_tools repo directly (not a fork).

**Comment by christophebedard** [comment]
If you "merge" this PR and it doesn't do a fast-forward merge/rebase, then the commit that ends up on the `jazzy` branch will not be the same commit as the commit in this PR (i.e., different SHA), so the tag you created will point to a commit that is not on the `jazzy` branch, which will create issues when you try to release with `bloom`.

Since you've already tagged the commit in this PR, just make sure it refers to the commit on the `jazzy` branch after merging this PR. If not, just re-create the tag using the commit on the `jazzy` branch.

Is this clearer?

**Comment by MichaelOrlov** [comment]
@christophebedard Ok, got it.
Yeah, I have had some issues with the tags when doing a bloom release in the past and was going to doublecheck where the new tag pointing out after the merge anyway.
Thanks for the fair warning.

**Comment by christophebedard** [comment]
The commit for this PR on `jazzy` is 834a70d3d164cca2b9f4160f5737ee1c2d093feb, which is different from the commit for which you created the `1.3.1` tag: https://github.com/ros-tooling/topic_tools/releases/tag/1.3.1 (29ff91fd54b032e0925d58d3b7f9c9711c6cf85d).

So yeah you need to re-create it.

**Comment by MichaelOrlov** [comment]
Thanks for catching it up - updated.

**Comment by MichaelOrlov** [comment]
Rosdistro PR https://github.com/ros/rosdistro/pull/42710 was merged

**Pull request merged**
