### PR TITLE
Fix windows warnings

### PR DESCRIPTION
**Pull request by emersonknapp**
Discovered in https://ci.ros2.org/job/ci_windows/19826/ via https://github.com/ros-tooling/topic_tools/pull/68

### CODE REVIEW

**Review by christophebedard — APPROVED** [review]
Looks good to me with green CI (at least local GitHub CI for Linux).

**Comment by emersonknapp** [comment]
I'll run full ci.ros2.org on this to actually look for greens across the board, then can backport and make sure Humble/Iron also all greens, then will cut releases with the new branches

**Comment by emersonknapp** [comment]
Pulls: ros-tooling/topic_tools#71
Gist: https://gist.githubusercontent.com/emersonknapp/64914eb5816cc95ae84edff9be760aac/raw/e985fc1b6d3ddc0aa3a43345a47c76e4d523498b/ros2.repos
BUILD args:  --packages-above-and-dependencies topic_tools
TEST args:  --packages-above topic_tools
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12337
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19089/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13613/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19832/)

**Comment by emersonknapp** [comment]
Rebuild above 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19093/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13614/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19833/)

**Comment by emersonknapp** [comment]
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19837/)

**Comment by emersonknapp** [comment]
@mergifyio backport humble iron

**Pull request merged**
