### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by jaagut**
This PR contains few updates to the `README.md` file.

The most relevant changes are updates to the parameter descriptions, mainly of `Throttle` and `Delay`. They seemed to be outdated.
Additionally, a list of all components including clickable references to the detailed sections and a short description has been introduced.

Other minor changes are:
- Update the `wiki.ros.org` URL to https, previously http
- Specify the language `shell` for commands, as recommended for Markdown
- Consistent punctuation in component

### CODE REVIEW

**Review by emersonknapp — APPROVED** [review]
thanks for helping improve documentation

**Comment by emersonknapp** [comment]
> During this update, I noticed, the Delay node does not implement the lazy parameter. Is that correct and intended?

Mainly this package has been a `lazy` port of features by folks as they are needed, so I'm guessing just nobody put in the effort to port it yet :)

**Comment by jaagut** [comment]
Force-pushed fixes for commit sign-offs...

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport humble

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport iron

**Pull request merged**
