### PR TITLE
fix: install python executables again

### PR DESCRIPTION
**Pull request by pschnattinger**
- This PR addresses issue https://github.com/ros-tooling/topic_tools/issues/114

### CODE REVIEW

**Comment by pschnattinger** [comment]
this was introduced with https://github.com/ros-tooling/topic_tools/commit/ad48bc00b0f08cca2170079ee44304bacc0786d2

**Comment by christophebedard** [comment]
Did you give it a try? Just to make sure that `transform` is indeed back.

**Comment by pschnattinger** [comment]
yes works again

```
virtual@pfs-thinkpad / $ ros2 run topic_tools transform --help
usage: transform [-h] [-i MODULES [MODULES ...]] [--wait-for-start]
                 [--qos-profile {unknown,default,system_default,sensor_data,services_default,parameters,parameter_events,action_status_default,best_available}] [--qos-depth N]
                 [--qos-history {system_default,keep_last,keep_all,unknown}] [--qos-reliability {system_default,reliable,best_effort,unknown,best_available}]
                 [--qos-durability {system_default,transient_local,volatile,unknown,best_available}] [--field FIELD]
                 input output_topic output_type expression

Apply a Python operation to a topic.

A node is created that subscribes to a topic,
applies a Python expression to the topic (or topic
field) message "m", and publishes the result
through another topic.

Usage:
	ros2 run topic_tools transform <input topic> <output topic> <output type> [<expression on m>] [--import numpy tf] [--field <topic_field>]

Example:
	ros2 run topic_tools transform /imu --field orientation /norm std_msgs/Float64"std_msgs.msg.Float64(data=sqrt(sum(array([m.x, m.y, m.z, m.w]))))" --import std_msgs

positional arguments:
  input                 Input topic or topic field.
  output_topic          Output topic.
  output_type           Output topic type.
  expression            Python expression to apply on the input message "m".

options:
  -h, --help            show this help message and exit
  -i MODULES [MODULES ...], --import MODULES [MODULES ...]
                        List of Python modules to import.
  --wait-for-start      Wait for input messages.
  --qos-profile {unknown,default,system_default,sensor_data,services_default,parameters,parameter_events,action_status_default,best_available}
                        Quality of service preset profile to subscribe with (default: sensor_data)
  --qos-depth N         Queue size setting to subscribe with (overrides depth value of --qos-profile option)
  --qos-history {system_default,keep_last,keep_all,unknown}
                        History of samples setting to subscribe with (overrides history value of --qos-profile option, default: keep_last)
  --qos-reliability {system_default,reliable,best_effort,unknown,best_available}
                        Quality of service reliability setting to subscribe with (overrides reliability value of --qos-profile option, default: Automatically match existing publishers )
  --qos-durability {system_default,transient_local,volatile,unknown,best_available}
                        Quality of service durability setting to subscribe with (overrides durability value of --qos-profile option, default: Automatically match existing publishers )
  --field FIELD         Transform a selected field of a message. Use '.' to select sub-fields. For example, to transform the orientation x field of a sensor_msgs/msg/Imu message: 'ros2 run topic_tools transform /imu --field orientatin.x'
```

**Review by MichaelOrlov — APPROVED** [review]
LGTM

**Comment by christophebedard** [comment]
Can you rebase and fix the conflicts in `topic_tools/CMakeLists.txt`?

**Comment by pschnattinger** [comment]
done and should be ready :)

**Review by christophebedard — APPROVED** [review]

**Comment by christophebedard** [comment]
Thanks for the PR!

**Comment by christophebedard** [comment]
@mergifyio backport jazzy

**Pull request merged**
