### PR TITLE
Feature/transform

### PR DESCRIPTION
**Pull request by wep21**
Add transform from https://github.com/ros/ros_comm/blob/noetic-devel/tools/topic_tools/scripts/transform
http://wiki.ros.org/topic_tools/transform

### CODE REVIEW

**Comment by emersonknapp** [comment]
My major concern here is that the Python linters are not run on this script - probably because it doesn't end in `.py`. I'd like to make sure to apply standard ROS 2 linters to all code here, at the very least (an actual functional test would be nice but I won't block on that).

Could you make it so that the linters run on this new source? Probably you could strip the `.py` extension and do a `chmod` on the file as part of the CMake `install` step.

**Comment by wep21** [comment]
@emersonknapp I use `ament_cmake_python` macro instead of pure cmake `install` and add entry points for `transform` executable. How about this modification?
Note: `SCRIPTS_DESTINATION` argument is only available for `rolling`.
https://github.com/ament/ament_cmake/blob/a51ed2214ce96fe0ef1ee00455cb03ba14bd52f1/ament_cmake_python/cmake/ament_python_install_package.cmake#L44
https://github.com/ament/ament_cmake/blob/a803f8534312a3b6dbe8a274bf788955d40d0eaa/ament_cmake_python/cmake/ament_python_install_package.cmake#L37

**Review by emersonknapp — APPROVED** [review]
Thanks for making the change - I think this looks good to me

**Comment by mateusz-lichota** [comment]
@emersonknapp @wep21 , the fact that `SCRIPTS_DESTINATION` is used means that the package doesn't build correctly on galactic. Is that the desired behavior?

**Comment by wep21** [comment]
@mateusz-lichota I created a PR to address the isseu you suggested. Please check it out.

**Comment by emersonknapp** [comment]
Thanks for the work @wep21 - I have merged that PR

**Pull request merged**
