### PR TITLE
Make compatible with windows

### PR DESCRIPTION
**Pull request by anrp-tri**

### CODE REVIEW

**Comment by christophebedard** [comment]
Thanks for the PR! I've changed the base branch from `humble` to `main`. We'll backport to `humble` after this is merged. Could you just rebase your commit on the `main` branch? And also could you sign off your commit (`git commit --amend --no-edit -s`)?

**Comment by anrp-tri** [comment]
Done.

**Review by emersonknapp — APPROVED** [review]

**Comment by emersonknapp** [comment]
Pulls: ros-tooling/topic_tools#68
Gist: https://gist.githubusercontent.com/emersonknapp/6344476197d93205d189a2cf57bae540/raw/e67e903ac4f5f0625e6562d407542891cc75041f/ros2.repos
BUILD args:  --packages-above-and-dependencies topic_tools
TEST args:  --packages-above topic_tools
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12331
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19080/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13607/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19826/)

**Comment by emersonknapp** [comment]
Thanks for this patch - we haven't run Windows CI on this package yet, I'm glad it looks like only a small change to make it go. Looking forward to seeing if the CI reveals any extra things. However if this makes build go from red->yellow that's still fine by me and I'll be happy to merge it, even if not green

**Comment by emersonknapp** [comment]
@mergifyio backport iron humble

**Pull request merged**
