### PR TITLE
Use Ubuntu Noble distro for ci on rolling

### PR DESCRIPTION
**Pull request by MichaelOrlov**
- Attempt to address CMake failure on CI:
```
CMake Error at CMakeLists.txt:14 (find_package):
2024-06-10T19:43:53.5674842Z   By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
2024-06-10T19:43:53.5675606Z   has asked CMake to find a package configuration file provided by
2024-06-10T19:43:53.5676188Z   "ament_cmake", but CMake did not find one.
2024-06-10T19:43:53.5676497Z 
```
- Follow up on https://github.com/ros-tooling/topic_tools/pull/106#discussion_r1635157210

### CODE REVIEW

**Comment by christophebedard** [comment]
We could just merge #106, since it has those changes.

**Comment by MichaelOrlov** [comment]
@christophebedard I would prefer to fix CI scripts in a separate PR.

**Review by clalancette — APPROVED** [review]

**Comment by christophebedard** [comment]
Sure, that's fine with me.

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport jazzy

**Comment by MichaelOrlov** [comment]
@christophebedard @clalancette There is no `jazzy` branch for `topic_tools`. Did we miss something?

**Comment by christophebedard** [comment]
This repo isn't part of the ROS 2 core, and no one created the branch.

**Comment by christophebedard** [comment]
When we do create the `jazzy` branch, we should update the branch name in rosdistro https://github.com/ros/rosdistro/blob/258800ad9291feb269da3fcbbe8764b98fc94a6b/jazzy/distribution.yaml#L7595 and in the release repo https://github.com/ros2-gbp/topic_tools-release/blob/d3ec3544366ec4e953ca4d5c899e70b4ed5919d9/tracks.yaml#L80

**Comment by christophebedard** [comment]
1. :heavy_check_mark: Create `jazzy` branch from `rolling` in this repo, and add protection here: https://github.com/ros-tooling/topic_tools/settings/branches
2. Change `version: rolling` in the rosdistro `jazzy/distribution.yaml` entry for `topic_tools` to `version: jazzy`: https://github.com/ros/rosdistro/blob/258800ad9291feb269da3fcbbe8764b98fc94a6b/jazzy/distribution.yaml#L7595-L7612
3. Change `devel_branch` for Jazzy from `rolling` to `jazzy` in the release repo: https://github.com/ros2-gbp/topic_tools-release/blob/d3ec3544366ec4e953ca4d5c899e70b4ed5919d9/tracks.yaml#L95

At this point, Rolling and Jazzy will still have the same version of `topic_tools`, which is fine.

1. Create a new release for Rolling on `rolling`, bumping the major version
2. Create a new release for Jazzy on `jazzy`, bumping the minor version

**Pull request merged**
