### PR TITLE
Apply race fix to mux publisher

### PR DESCRIPTION
**Pull request by andrewbest-tri**
Apply fix described in https://github.com/ros-tooling/topic_tools/pull/56 to mux_node

### CODE REVIEW

**Comment by christophebedard** [comment]
Looks good, could you just sign-off your commit?

**Comment by andrewbest-tri** [comment]
> Looks good, could you just sign-off your commit?

Done. Thanks for quick review.

**Review by christophebedard — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport humble

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport iron

**Pull request merged**
