### PR TITLE
Separate relay into exec and library

### PR DESCRIPTION
**Pull request by wep21**
Separate `relay` into exec and library to load `relay` as compoent.

### CODE REVIEW

**Comment by emersonknapp** [comment]
This PR doesn't do the `rclcpp_components` portion of creating a component - is that the goal here?

**Comment by wep21** [comment]
> This PR doesn't do the rclcpp_components portion of creating a component
I'm sorry, I forgot registering `relay`, so I fixed it at https://github.com/ros-tooling/topic_tools/pull/15/commits/ce7406576baf90bca679938edbc92eeb7ee090d5.
A user can load `relay` as a component by a user defined launch file as below.
```
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import LaunchConfigurationEquals
from launch.conditions import LaunchConfigurationNotEquals
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import ComposableNodeContainer
from launch_ros.actions import LoadComposableNodes
from launch_ros.descriptions import ComposableNode


def generate_launch_description():
    composable_nodes = [
        ComposableNode(
            package='topic_tools',
            plugin='topic_tools::RelayNode',
            name='relay_node',
            parameters=[{
                'input_topic': 'chatter'
            }]
        ),
    ]

    arg_container = DeclareLaunchArgument(
        name='container', default_value='',
        description=(
            'Name of an existing node container to load launched nodes into. '
            'If unset, a new container will be created.'
        )
    )

    # If an existing container is not provided, start a container and load nodes into it
    container = ComposableNodeContainer(
        condition=LaunchConfigurationEquals('container', ''),
        name='relay_container',
        namespace='',
        package='rclcpp_components',
        executable='component_container',
        composable_node_descriptions=composable_nodes,
        output='screen'
    )

    # If an existing container name is provided, load composable nodes into it
    # This will block until a container with the provided name is available and nodes are loaded
    load_composable_nodes = LoadComposableNodes(
        condition=LaunchConfigurationNotEquals('container', ''),
        composable_node_descriptions=composable_nodes,
        target_container=LaunchConfiguration('container'),
    )

    return LaunchDescription([
        arg_container,
        container,
        load_composable_nodes,
    ])
```

**Review by emersonknapp — APPROVED** [review]
LGTM

**Comment by emersonknapp** [comment]
Ah - that's the problem - this is building against Rolling. We can branch off for Galactic if we want to make a release for that distro - but the main development branch will always target Rolling (which makes it trivial to release into new distros).

**Comment by wep21** [comment]
@emersonknapp I'm sorry, I found out the problem and fixed it.(maybe cache is not cleared.)

**Pull request merged**
